"use client";

import { useState, useEffect, useRef, useCallback, useTransition } from "react";
import { getSOP, saveSOP, generateSOPDraft } from "./actions";
import { toast } from "react-toastify";
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
import { TDocumentDefinitions } from "pdfmake/interfaces";
import { useProfileCompleteness } from "@/hooks/useProfileCompleteness";
import RequireProfile from "@/components/providers/RequireProfile";

// Assign vfs fonts
(pdfMake as any).vfs = pdfFonts;

export default function SopPage() {
  // ----- State -----
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [exporting, setExporting] = useState(false);

  const { profile, profileComplete, missingFields, loading: profileLoading } = useProfileCompleteness();

  // Autosave debounce
  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [isPending, startTransition] = useTransition();

  // ----- Generate fresh draft -----
  const handleGenerate = useCallback(async (silent = false) => {
    setGenerating(true);
    try {
      const result = await generateSOPDraft();
      if (result.success && result.content) {
        setContent(result.content);
        if (result.title) setTitle(result.title);
        if (!silent) toast.success("Generated With Pathway AI.");
      } else {
        toast.error(result.error || "Failed to generate.");
      }
    } catch (error) {
      toast.error("Network error while generating.");
    } finally {
      setGenerating(false);
    }
  }, []);

  // ----- Load / create SOP on mount -----
  useEffect(() => {
    (async () => {
      try {
        const { success, data, error } = await getSOP();
        if (success && data) {
          if (data.id) {
            setTitle(data.title || "");
            setContent(data.content || "");
          } else {
            await handleGenerate(true);
          }
        } else if (error) {
          toast.error(error || "Failed to load SOP. A new document will be created.");
        }
      } catch {
        toast.error("Network error while loading your SOP.");
      } finally {
        setLoading(false);
      }
    })();
  }, [handleGenerate]);

  // ----- Autosave (2s debounce) -----
  const debouncedSave = useCallback(
    (newTitle: string, newContent: string) => {
      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
      saveTimerRef.current = setTimeout(() => {
        startTransition(async () => {
          setSaving(true);
          try {
            const { success, error } = await saveSOP(newTitle, newContent);
            if (!success) toast.error(error || "Autosave failed");
          } catch {
            toast.error("Network error while saving.");
          } finally {
            setSaving(false);
          }
        });
      }, 2000);
    },
    []
  );

  useEffect(() => {
    if (!loading && !profileLoading && profileComplete) {
      debouncedSave(title, content);
    }
    return () => {
      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    };
  }, [title, content, loading, profileLoading, profileComplete, debouncedSave]);

  // ----- Export as PDF -----
  const handleExport = () => {
    if (!content.trim()) {
      toast.error("Nothing to export.");
      return;
    }
    setExporting(true);
    try {
      const docDefinition = {
        pageSize: "A4",
        pageMargins: [40, 40, 40, 40],
        content: [
          { text: title || "Statement of Purpose", style: "title", margin: [0, 0, 0, 20], alignment: "center" },
          { text: content, style: "body", lineHeight: 1.5 },
        ],
        footer: (currentPage: number, pageCount: number) => ({
          text: "Generated by Pathway AI",
          style: "footer",
          alignment: "center",
          margin: [0, 0, 0, 20],
        }),
        styles: {
          title: { font: "Roboto", fontSize: 18, bold: true, color: "#1b1b24" },
          body: { font: "Roboto", fontSize: 11, color: "#1b1b24" },
          footer: { font: "Roboto", fontSize: 8, color: "#999999", italics: true },
        },
      } as TDocumentDefinitions;

      const safeTitle = title
        ? title.replace(/[^a-z0-9]/gi, "_").toLowerCase()
        : "statement_of_purpose";
      pdfMake.createPdf(docDefinition).download(`${safeTitle}.pdf`);
      toast.success("PDF downloaded.");
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate PDF.");
    } finally {
      setExporting(false);
    }
  };

  // ----- Derived values -----
  const wordCount = content.trim() ? content.trim().split(/\s+/).length : 0;
  const maxWords = 800;
  const progress = Math.min(100, (wordCount / maxWords) * 100);

  // ----- Loading state (profile + sop) -----
  if (loading || profileLoading || generating) {
    return (
      <div className="flex items-center justify-center h-[calc(100vh-8rem)]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
      </div>
    );
  }

  // ----- Main UI (wrapped in profile guard) -----
  return (
    <RequireProfile
      profileComplete={profileComplete}
      missingFields={missingFields}
      message="The SOP builder uses your profile details to generate personalised statements. Please fill in all required fields to continue."
    >
      <div className="min-h-screen md:h-[calc(100vh-8rem)] flex flex-col gap-6 overflow-hidden">
        {/* Editor area */}
        <section className="grow flex flex-col bg-surface-container-lowest relative overflow-y-auto">
          <div className="max-w-7xl mx-auto w-full py-6 md:py-12 pb-24 px-4 md:px-12">
            {/* Header: Title + AI buttons */}
            <div className="flex flex-col sm:flex-row items-start justify-between gap-4 mb-6">
              <div className="flex-1 w-full">
                <input
                  className="bg-transparent focus:outline-none border-none p-0 text-2xl md:text-headline-lg font-bold text-on-surface focus:ring-0 w-full mb-2"
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="[Enter Title Here]"
                />
                <span className="text-[10px] text-on-surface-variant opacity-60">
                  Auto‑save is on
                </span>
              </div>

              <div className="flex gap-2 shrink-0">
                <button
                  onClick={() => handleGenerate(false)}
                  disabled={generating}
                  className="bg-primary text-on-primary px-3 py-2 md:px-4 md:py-2 rounded-full flex items-center gap-2 text-xs md:text-sm font-bold hover:shadow-lg transition-all active:scale-95 disabled:opacity-50 cursor-pointer"
                >
                  {generating ? (
                    <>
                      <span className="material-symbols-outlined text-[16px] md:text-[20px] animate-spin">sync</span>
                      Generating…
                    </>
                  ) : (
                    "Generate"
                  )}
                </button>
              </div>
            </div>

            {/* Main editor area */}
            <textarea
              className="w-full h-[50vh] md:h-[60vh] bg-transparent border-none resize-none focus:ring-0 text-base md:text-body-lg text-on-surface leading-relaxed p-0 outline-none"
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="[Start writing your Statement of Purpose here...]"
            />
          </div>
        </section>

        {/* Floating Export Button */}
        <div className="fixed bottom-4 right-4 md:bottom-8 md:right-8 z-50">
          <button
            onClick={handleExport}
            disabled={exporting}
            className="flex items-center gap-2 px-5 py-3 md:px-8 md:py-4 bg-primary text-white rounded-full font-bold shadow-xl shadow-primary/20 hover:bg-primary/90 transform hover:-translate-y-1 transition-all active:scale-95 cursor-pointer disabled:opacity-70 disabled:hover:translate-y-0 disabled:cursor-not-allowed select-invert text-sm md:text-base"
          >
            {exporting ? (
              <>
                <span className="material-symbols-outlined animate-spin">sync</span>
                Exporting...
              </>
            ) : (
              <>
                <span className="material-symbols-outlined select-invert">download</span>
                Export PDF
              </>
            )}
          </button>
        </div>
      </div>
    </RequireProfile>
  );
}